# Generated by Django 2.2.8 on 2020-06-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('In Progress', 'In Progress'), ('To Verify', 'To Verify'), ('Bugged', 'Buggged'), ('Completed', 'Completed')], default='To-Do', max_length=30),
        ),
    ]
