# Generated by Django 2.2.8 on 2020-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200618_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='task_progress_prior',
            field=models.CharField(default='To Do', max_length=200),
        ),
    ]
