# Generated by Django 2.2.8 on 2020-06-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_logs_task_progress_prior'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
        migrations.AddField(
            model_name='task',
            name='essential',
            field=models.BooleanField(default=False),
        ),
    ]
