# Generated by Django 2.2.8 on 2020-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200618_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='a test project', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.CharField(default='test notes', max_length=500),
            preserve_default=False,
        ),
    ]
