# Generated by Django 2.2.8 on 2020-06-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200618_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
