# Generated by Django 2.2.8 on 2020-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='essential_percent_complete',
            field=models.IntegerField(default=0),
        ),
    ]
